# Generated by Django 5.2.8 on 2025-12-01 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre comercial del producto.', max_length=200, verbose_name='Nombre del Producto')),
                ('description', models.TextField(help_text='Descripción detallada del producto.', verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de Venta')),
                ('stock', models.IntegerField(help_text='Número de unidades en almacén.', verbose_name='Stock Disponible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Producto',
            },
        ),
    ]
